services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "8003:8003"
    volumes:
      - ../broker/mosquitto.conf:/mosquitto/config/mosquitto.conf